# -*- coding: utf-8 -*-
"""HTML summary report builder.

Self-contained HTML — single file with inline CSS and inline base64
thumbnails. The user can email it, post it to SharePoint, or print it
to PDF directly from any browser (Ctrl+P → Save as PDF). That last
trick is why this module exists: IronPython 2.7 has no maintained
pure-Python PDF library, but every browser turns HTML into PDF for
free, so we ship HTML and inherit PDF-ability.

Designed for sharing with non-Revit consumers (clients, GCs, project
managers). Same `clashes`, `filter_predicate`, `project_name`
arguments as `excel_summary.build_xlsx` so the Reports script can
dispatch to either by selecting the right module.

The HTML structure:
  * dbHMS-branded header (slate bar, "db | HMS" wordmark)
  * Run metadata (project, generated-at, applied filter)
  * Summary cards — counts by status + by trade
  * Per-clash detail blocks: thumbnail + element refs + status / trade /
    test / comments / history snippet

Pure-data — no Revit, no WPF imports. Parses cleanly in CPython 3 for
the test suite and runs the same way under IronPython 2.7 in pyRevit.
"""

import base64
import codecs
import os


SCHEMA_VERSION = 1


# Status pill colors — match the Browser's STATUS_BRUSHES so HTML and
# in-app render the same way.
_STATUS_COLORS = {
    'Open':     '#E53E3E',
    'Reviewed': '#D69E2E',
    'Approved': '#2B6CB0',
    'Resolved': '#38A169',
}

_TRADE_COLORS = {
    'Mechanical':       ('#DBE5EE', '#3D5A75'),
    'Electrical':       ('#EDE2C6', '#7A5C1F'),
    'Plumbing':         ('#D5E5E0', '#3F6D6B'),
    'Fire Protection':  ('#EAD2D2', '#7A4040'),
    'Technology':       ('#E0D5E8', '#5E4878'),
    'Architectural':    ('#E5E0D5', '#605A4D'),
    'Structural':       ('#D8DCE0', '#3E454F'),
}

# Default trade pill colors when the trade isn't in the lookup.
_TRADE_DEFAULT_BG = '#EDF2F7'
_TRADE_DEFAULT_FG = '#4A5568'


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_html(clashes, out_path, filter_predicate=None,
               project_name=None, viewpoints_dir=None,
               generated_by=None, filter_description=None,
               include_thumbnails=True, test_name_lookup=None,
               now_iso=None):
    """Write a self-contained HTML report to `out_path`.

    Args:
        clashes              - list of clash dicts (clashes.json `clashes`
                               field).
        out_path             - destination filename (`.html` extension).
        filter_predicate     - optional callable(clash_dict) -> bool. Only
                               clashes that pass are included. None means
                               include everything.
        project_name         - human-friendly project label for the header.
        viewpoints_dir       - directory containing per-clash thumbnail
                               PNGs (`<clash-id>.png`). When set AND
                               `include_thumbnails`, each clash's image is
                               embedded as a base64 data URI. Set to None
                               to skip even if thumbnails exist on disk.
        generated_by         - user name for the "Generated by:" line.
        filter_description   - human-readable description of the active
                               filter (e.g. "Mechanical only, Open + Reviewed").
        include_thumbnails   - master switch for embedding images. Off
                               makes a much smaller file (useful for
                               huge projects).
        test_name_lookup     - dict mapping `test_id` → display name. The
                               clash dict only stores the id; the name
                               lives in the global test library. Caller
                               should pass `{tid: name for ...}` from
                               `persistence.read_global_test_library`.
        now_iso              - timestamp string for the "Generated at:"
                               line. None → use the current time. Tests
                               pass a fixed value for deterministic
                               output.

    Returns the count of clashes written (after filtering).
    """
    if test_name_lookup is None:
        test_name_lookup = {}
    if now_iso is None:
        from datetime import datetime
        now_iso = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    filtered = []
    for c in clashes or []:
        if not isinstance(c, dict):
            continue
        if filter_predicate is not None:
            try:
                if not filter_predicate(c):
                    continue
            except Exception:
                continue
        filtered.append(c)

    counts_by_status, counts_by_trade = _compute_counts(filtered)

    body = _render_full_html(
        clashes=filtered,
        project_name=project_name,
        generated_by=generated_by,
        generated_at=now_iso,
        filter_description=filter_description,
        counts_by_status=counts_by_status,
        counts_by_trade=counts_by_trade,
        viewpoints_dir=viewpoints_dir,
        include_thumbnails=include_thumbnails,
        test_name_lookup=test_name_lookup,
    )

    out_dir = os.path.dirname(out_path)
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    with codecs.open(out_path, "w", "utf-8") as f:
        f.write(body)
    return len(filtered)


# ---------------------------------------------------------------------------
# Counts
# ---------------------------------------------------------------------------

def _compute_counts(clashes):
    """Return (counts_by_status, counts_by_trade) — two dicts mapping
    bucket name → count. Statuses include all four standard values
    even when zero (so the summary section shows "Approved: 0" rather
    than omitting the bucket)."""
    counts_by_status = {'Open': 0, 'Reviewed': 0, 'Approved': 0, 'Resolved': 0}
    counts_by_trade = {}
    for c in clashes:
        status = c.get('status') or 'Open'
        counts_by_status[status] = counts_by_status.get(status, 0) + 1
        trade = c.get('assignee') or 'Unassigned'
        counts_by_trade[trade] = counts_by_trade.get(trade, 0) + 1
    return counts_by_status, counts_by_trade


# ---------------------------------------------------------------------------
# HTML rendering
# ---------------------------------------------------------------------------

def _render_full_html(clashes, project_name, generated_by, generated_at,
                       filter_description, counts_by_status, counts_by_trade,
                       viewpoints_dir, include_thumbnails, test_name_lookup):
    parts = []
    parts.append(_RENDER_HEAD)
    parts.append(_render_header(project_name, generated_by, generated_at,
                                 filter_description, len(clashes)))
    parts.append(_render_summary(counts_by_status, counts_by_trade))
    parts.append('<section class="clashes">')
    if not clashes:
        parts.append('<div class="empty">No clashes match the selected filter.</div>')
    for c in clashes:
        parts.append(_render_clash(c, viewpoints_dir, include_thumbnails,
                                    test_name_lookup))
    parts.append('</section>')
    parts.append(_RENDER_FOOT)
    return ''.join(parts)


def _render_header(project_name, generated_by, generated_at,
                    filter_description, total_count):
    pieces = []
    pieces.append('<header class="dbhms-header">')
    pieces.append('  <div class="title-block">')
    pieces.append('    <div class="title">Clash Report</div>')
    pieces.append('    <div class="subtitle">{}</div>'.format(
        _esc(project_name or 'Untitled project')))
    pieces.append('  </div>')
    pieces.append('  <div class="wordmark">')
    pieces.append('    <span class="wm-blue">db</span>')
    pieces.append('    <span class="wm-divider"> | </span>')
    pieces.append('    <span class="wm-blue">HMS</span>')
    pieces.append('  </div>')
    pieces.append('</header>')
    pieces.append('<section class="metadata">')
    pieces.append('  <div><strong>Total clashes:</strong> {}</div>'.format(
        total_count))
    if filter_description:
        pieces.append('  <div><strong>Filter:</strong> {}</div>'.format(
            _esc(filter_description)))
    pieces.append('  <div><strong>Generated:</strong> {}</div>'.format(
        _esc(generated_at)))
    if generated_by:
        pieces.append('  <div><strong>By:</strong> {}</div>'.format(
            _esc(generated_by)))
    pieces.append('</section>')
    return '\n'.join(pieces) + '\n'


def _render_summary(counts_by_status, counts_by_trade):
    pieces = []
    pieces.append('<section class="summary">')
    pieces.append('  <div class="summary-block">')
    pieces.append('    <h2>By status</h2>')
    pieces.append('    <ul class="summary-list">')
    for status in ('Open', 'Reviewed', 'Approved', 'Resolved'):
        n = counts_by_status.get(status, 0)
        color = _STATUS_COLORS.get(status, '#A0AEC0')
        pieces.append(
            '      <li><span class="dot" style="background:{};"></span>'
            '<span class="label">{}</span><span class="count">{}</span></li>'
            .format(color, _esc(status), n))
    pieces.append('    </ul>')
    pieces.append('  </div>')
    pieces.append('  <div class="summary-block">')
    pieces.append('    <h2>By trade</h2>')
    pieces.append('    <ul class="summary-list">')
    # Sorted descending by count for readability.
    items = sorted(counts_by_trade.items(), key=lambda kv: -kv[1])
    if not items:
        pieces.append('      <li class="empty-list">(no clashes)</li>')
    for trade, n in items:
        bg, fg = _TRADE_COLORS.get(trade, (_TRADE_DEFAULT_BG, _TRADE_DEFAULT_FG))
        pieces.append(
            '      <li><span class="trade-pill" style="background:{};color:{};">'
            '{}</span><span class="count">{}</span></li>'
            .format(bg, fg, _esc(trade), n))
    pieces.append('    </ul>')
    pieces.append('  </div>')
    pieces.append('</section>')
    return '\n'.join(pieces) + '\n'


def _render_clash(clash, viewpoints_dir, include_thumbnails, test_name_lookup):
    seq = clash.get('seq') or '?'
    status = clash.get('status') or 'Open'
    trade = clash.get('assignee') or 'Unassigned'
    test_id = clash.get('test_id')
    test_name = test_name_lookup.get(test_id) or '(unknown test)'
    ref_a = clash.get('ref_a') or {}
    ref_b = clash.get('ref_b') or {}
    comments = clash.get('comments') or []
    history = clash.get('history') or []
    kind = (clash.get('kind') or 'hard').lower()

    status_color = _STATUS_COLORS.get(status, '#A0AEC0')
    trade_bg, trade_fg = _TRADE_COLORS.get(
        trade, (_TRADE_DEFAULT_BG, _TRADE_DEFAULT_FG))

    img_html = ''
    if include_thumbnails and viewpoints_dir:
        img_data_uri = _read_thumbnail_data_uri(
            clash.get('id'), viewpoints_dir)
        if img_data_uri:
            img_html = (
                '<div class="clash-thumb">'
                '<img alt="Clash #{} viewpoint" src="{}"/></div>'.format(
                    _esc(seq), img_data_uri))

    pieces = []
    pieces.append('<article class="clash">')
    pieces.append('  <div class="clash-head">')
    pieces.append(
        '    <span class="clash-num">Clash #{}</span>'
        '    <span class="status-pill" style="background:{};">{}</span>'
        '    <span class="trade-pill" style="background:{};color:{};">{}</span>'
        '    <span class="kind">{}</span>'.format(
            _esc(seq), status_color, _esc(status),
            trade_bg, trade_fg, _esc(trade), _esc(kind.upper())))
    pieces.append('  </div>')
    pieces.append('  <div class="clash-body">')
    if img_html:
        pieces.append('    ' + img_html)
    pieces.append('    <div class="clash-meta">')
    pieces.append('      <div class="test-name">{}</div>'.format(_esc(test_name)))
    pieces.append('      <div class="elem-row"><span class="elem-label">A:</span> {}</div>'.format(
        _esc(ref_a.get('name') or 'unnamed')))
    pieces.append('      <div class="elem-id mono">id {} {}</div>'.format(
        _esc(ref_a.get('element_id') or '?'),
        _esc('— ' + (ref_a.get('source') or 'host'))))
    pieces.append('      <div class="elem-row"><span class="elem-label">B:</span> {}</div>'.format(
        _esc(ref_b.get('name') or 'unnamed')))
    pieces.append('      <div class="elem-id mono">id {} {}</div>'.format(
        _esc(ref_b.get('element_id') or '?'),
        _esc('— ' + (ref_b.get('source') or 'host'))))
    pieces.append('    </div>')
    pieces.append('  </div>')

    if comments:
        pieces.append('  <div class="clash-comments">')
        pieces.append('    <h3>Comments ({})</h3>'.format(len(comments)))
        for cm in comments:
            pieces.append(
                '    <div class="comment"><span class="cm-when mono">{}</span>'
                ' <span class="cm-author">{}</span><div class="cm-body">{}</div></div>'
                .format(_esc(_short_when(cm.get('at'))),
                        _esc(cm.get('author') or 'unknown'),
                        _esc(cm.get('body') or '')))
        pieces.append('  </div>')

    if history:
        pieces.append('  <div class="clash-history">')
        pieces.append('    <h3>History ({})</h3>'.format(len(history)))
        pieces.append('    <ul>')
        for h in history:
            pieces.append(
                '      <li><span class="h-when mono">{}</span>'
                ' <span class="h-author">{}</span> '
                '<span class="h-action">{}</span></li>'.format(
                    _esc(_short_when(h.get('at'))),
                    _esc(h.get('author') or 'unknown'),
                    _esc(_format_history_action(h))))
        pieces.append('    </ul>')
        pieces.append('  </div>')

    pieces.append('</article>')
    return '\n'.join(pieces) + '\n'


def _format_history_action(history_entry):
    action = history_entry.get('action') or ''
    before = history_entry.get('before')
    after = history_entry.get('after')
    if before is not None and after is not None:
        return '{}: {} → {}'.format(action, before, after)
    return action


def _short_when(iso_str):
    """Format an ISO timestamp as a short "YYYY-MM-DD HH:MM" string for
    display. Returns the raw input if it's not ISO-shaped (defensive)."""
    if not iso_str:
        return ''
    s = str(iso_str)
    if 'T' not in s:
        return s
    date_part, time_part = s.split('T', 1)
    if '.' in time_part:
        time_part = time_part.split('.', 1)[0]
    if time_part.endswith('Z'):
        time_part = time_part[:-1]
    return '{} {}'.format(date_part, time_part[:5])


# ---------------------------------------------------------------------------
# Thumbnails
# ---------------------------------------------------------------------------

def _read_thumbnail_data_uri(clash_id, viewpoints_dir):
    """Read the per-clash thumbnail PNG and return a `data:image/png;base64,...`
    URI suitable for inline `<img src=...>` use. Returns '' if missing or
    unreadable.
    """
    if not clash_id or not viewpoints_dir:
        return ''
    path = os.path.join(viewpoints_dir, '{}.png'.format(clash_id))
    if not os.path.isfile(path):
        return ''
    try:
        with open(path, 'rb') as f:
            data = f.read()
    except Exception:
        return ''
    encoded = base64.b64encode(data)
    if isinstance(encoded, bytes):
        encoded = encoded.decode('ascii')
    return 'data:image/png;base64,' + encoded


# ---------------------------------------------------------------------------
# Escaping
# ---------------------------------------------------------------------------

def _esc(s):
    """HTML-escape a value. Handles None, ints, etc. by str()-ing first.
    Avoids importing `html` (Python 3) or `cgi` (deprecated in Python 3)
    to stay portable across IronPython 2.7 and CPython 3.
    """
    return (str(s if s is not None else '')
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;')
            .replace("'", '&#39;'))


# ---------------------------------------------------------------------------
# CSS + boilerplate
# ---------------------------------------------------------------------------

# Fully self-contained <head> + opening <body>. Inline CSS so the file
# doesn't depend on external assets — emails / SharePoint / whatever
# render it identically. Print-friendly: page break after each clash so
# Save-as-PDF produces clean per-clash pages.
_RENDER_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>dbHMS Clash Report</title>
<style>
  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: #F7FAFC;
    font-family: 'Segoe UI', Helvetica, Arial, sans-serif;
    font-size: 13px;
    color: #2D3748;
    line-height: 1.45;
  }
  .dbhms-header {
    background: #2D3748;
    color: white;
    padding: 20px 28px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .title-block .title {
    font-size: 22px;
    font-weight: 700;
  }
  .title-block .subtitle {
    font-size: 13px;
    color: #CBD5E0;
    margin-top: 3px;
  }
  .wordmark {
    opacity: 0.85;
    font-size: 32px;
    font-weight: 700;
  }
  .wordmark .wm-blue { color: #00BFFF; }
  .wordmark .wm-divider { color: #7A8FA6; font-weight: 300; }
  .metadata {
    padding: 14px 28px;
    background: white;
    border-bottom: 1px solid #E2E8F0;
    display: flex;
    flex-wrap: wrap;
    gap: 0 24px;
    color: #4A5568;
  }
  .metadata strong { color: #1A202C; }
  .summary {
    padding: 16px 28px;
    background: white;
    border-bottom: 1px solid #E2E8F0;
    display: flex;
    gap: 32px;
  }
  .summary-block { flex: 1; min-width: 220px; }
  .summary-block h2 {
    font-size: 13px;
    font-weight: 600;
    color: #4A5568;
    margin: 0 0 8px;
    text-transform: uppercase;
    letter-spacing: 0.6px;
  }
  .summary-list {
    list-style: none;
    padding: 0;
    margin: 0;
  }
  .summary-list li {
    display: flex;
    align-items: center;
    padding: 4px 0;
  }
  .summary-list .dot {
    display: inline-block;
    width: 10px;
    height: 10px;
    border-radius: 50%;
    margin-right: 8px;
  }
  .summary-list .label { flex: 1; }
  .summary-list .count {
    font-weight: 600;
    color: #1A202C;
    margin-left: 8px;
  }
  .clashes {
    padding: 16px 28px;
  }
  .empty {
    padding: 40px;
    text-align: center;
    color: #A0AEC0;
    font-style: italic;
  }
  .clash {
    background: white;
    border: 1px solid #E2E8F0;
    border-radius: 4px;
    padding: 12px 14px;
    margin-bottom: 12px;
    page-break-inside: avoid;
  }
  .clash-head {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 8px;
    flex-wrap: wrap;
  }
  .clash-num {
    font-weight: 700;
    font-size: 14px;
    color: #1A202C;
  }
  .status-pill {
    color: white;
    padding: 2px 10px;
    border-radius: 10px;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.4px;
  }
  .trade-pill {
    padding: 2px 10px;
    border-radius: 10px;
    font-size: 11px;
    font-weight: 600;
  }
  .kind {
    font-size: 11px;
    color: #A0AEC0;
    margin-left: auto;
    font-weight: 600;
  }
  .clash-body {
    display: flex;
    gap: 14px;
  }
  .clash-thumb {
    flex: 0 0 240px;
  }
  .clash-thumb img {
    width: 240px;
    height: auto;
    border: 1px solid #E2E8F0;
    border-radius: 3px;
    display: block;
  }
  .clash-meta {
    flex: 1;
  }
  .test-name {
    font-weight: 600;
    color: #1A202C;
    margin-bottom: 6px;
  }
  .elem-row {
    margin-top: 4px;
  }
  .elem-row .elem-label {
    font-weight: 600;
    color: #4A5568;
    margin-right: 4px;
  }
  .elem-id {
    font-size: 11px;
    color: #718096;
  }
  .mono {
    font-family: Consolas, 'Courier New', monospace;
  }
  .clash-comments,
  .clash-history {
    margin-top: 10px;
    padding-top: 10px;
    border-top: 1px dashed #E2E8F0;
  }
  /* Comments get a soft tinted block so they're easy to spot at a
     glance — they're often the most useful information on a clash
     for a meeting reviewer ("@Tom said it's intentional"), and the
     pre-tint version was easy to miss. */
  .clash-comments {
    background: #F0F9FF;
    border-left: 3px solid #2B6CB0;
    border-top: none;
    margin-top: 12px;
    padding: 8px 10px;
    border-radius: 0 3px 3px 0;
  }
  .clash-comments h3 {
    font-size: 11px;
    font-weight: 700;
    color: #2B6CB0;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin: 0 0 6px;
  }
  .clash-history h3 {
    font-size: 11px;
    font-weight: 600;
    color: #4A5568;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin: 0 0 6px;
  }
  .comment {
    padding: 5px 0;
  }
  .comment + .comment {
    border-top: 1px dashed #BEE3F8;
  }
  .cm-when {
    color: #4A5568;
    font-size: 11px;
    margin-right: 8px;
  }
  .h-when {
    color: #A0AEC0;
    font-size: 11px;
    margin-right: 8px;
  }
  .cm-author {
    font-weight: 700;
    color: #1A202C;
    margin-right: 8px;
  }
  .h-author {
    font-weight: 600;
    color: #2D3748;
    margin-right: 8px;
  }
  .cm-body {
    margin-top: 3px;
    color: #2D3748;
    font-size: 13px;
    line-height: 1.5;
  }
  .clash-history ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }
  .clash-history li {
    padding: 2px 0;
    font-size: 12px;
  }
  .h-action {
    color: #4A5568;
  }
  @media print {
    /* Print-specific tweaks: target ~3-4 clashes per Letter page.
       Default (screen) sizing is generous + readable on a monitor.
       For PDF, shrink everything ~30%, drop margins, and let multiple
       cards share a page. `page-break-inside: avoid` still prevents a
       single card from being split mid-content. */
    @page { margin: 0.4in; size: letter; }
    body { background: white; font-size: 10px; }
    .dbhms-header { padding: 10px 14px; }
    .title-block .title { font-size: 16px; }
    .title-block .subtitle { font-size: 10px; }
    .wordmark { font-size: 22px; }
    .metadata { padding: 8px 14px; gap: 0 16px; font-size: 10px; }
    .summary { padding: 8px 14px; gap: 18px; }
    .summary-block h2 { font-size: 10px; margin: 0 0 4px; }
    .summary-list li { padding: 1px 0; }
    .clashes { padding: 8px 14px; }
    .clash {
      padding: 6px 8px;
      margin-bottom: 6px;
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .clash-head { gap: 6px; margin-bottom: 4px; }
    .clash-num { font-size: 11px; }
    .status-pill, .trade-pill { font-size: 9px; padding: 1px 6px; }
    .clash-body { gap: 8px; }
    .clash-thumb { flex: 0 0 140px; }
    .clash-thumb img { width: 140px; }
    .clash-meta { font-size: 10px; }
    .test-name { font-size: 10px; margin-bottom: 3px; }
    .elem-row { margin-top: 1px; }
    .elem-id { font-size: 9px; }
    .clash-comments {
      margin-top: 6px;
      padding: 5px 7px;
    }
    .clash-history {
      margin-top: 5px;
      padding-top: 5px;
    }
    .clash-comments h3, .clash-history h3 {
      font-size: 10px;
      margin: 0 0 3px;
    }
    /* Keep comment bodies readable on PDF — they're the most
       useful information for an offline reviewer. Slightly larger
       than the surrounding 10px body. */
    .comment { padding: 2px 0; font-size: 10px; }
    .cm-body { font-size: 11px; margin-top: 2px; }
    .clash-history li { font-size: 9px; padding: 0; }
    .summary, .metadata, .dbhms-header { page-break-after: auto; }
  }
</style>
</head>
<body>
"""

_RENDER_FOOT = """</body>
</html>
"""
